server:
    error:
         include-stacktrace: ON_PARAM

spring:
    datasource: 
        url: jdbc:mysql://200.128.9.179:3306/AcademiaBD2023?createDatabaseIfNotExist=true
        username: remoto
        password: remoto
jpa:
    hibernate:
      ddl-auto: update
      