server:
    error:
         include-stacktrace: ON_PARAM

spring:
    datasource: 
        url: jdbc:mysql://10.28.0.35:3306/AcademiaBD2023?createDatabaseIfNotExist=true
        username: remoto
        password: remoto
jpa:
    hibernate:
      ddl-auto: update